### PR TITLE
Cleanup docker related files

### PR DESCRIPTION
**Pull request by blabno**

### CODE REVIEW

**Review by cbeams — CHANGES_REQUESTED** [review]
Thanks, @blabno. Please add a link from the main readme to `docker/README` so that interested users can better discover it, thanks. A bullet point under the "Further information section" would be fine.

**Review by cbeams — COMMENTED** [review]
utACK (and already merged)

@blabno, was it not possible or otherwise undesirable to move `docker-compose.yml` down into the `docker` directory as well?

For the record, I'll leave it to you (or others) to keep everything under the `docker` directory up to date.

Thanks!

**Comment by blabno** [comment]
@cbeams it is much handier for developers to keep it in project root directory cause you can invoke `docker-compose build` instead `docker-compose build -f docker/docker-compose.yml`.
That concerns all other `docker-compose` commands.

**Comment by cbeams** [comment]
Got it, thanks. All good.

**Pull request merged**
